services:
  nginx:
    image: nginx:latest
    container_name: app_nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    image: app_laravel
    container_name: app_laravel
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel
    entrypoint: ["/docker-entrypoint.sh"]

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
        - db-volume:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: "db"
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "user"
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
    ports:
        - 8081:5432
    networks:
      - laravel
    container_name: app_db

volumes:
  db-volume:

networks:
  laravel:
    driver: bridge
